app:
  name: ApexTracer-Lite
  version: 0.1.0
video:
  min_resolution: [1280, 720]
  max_fps: 240
detection:
  backend: onnx  # Force ONNX model for better accuracy
  min_conf: 0.05  # Lower confidence threshold
  max_candidates: 10
  tile_long_side: 1280
  min_radius_px: 3  # Slightly larger min radius to avoid noise
  max_radius_px: 50  # Increased max radius for better visibility

tracking:
  iou_threshold: 0.1
  max_gap_ms: 200
  process_noise: 5.0
  measurement_noise: 2.0

launch:
  speed_jump_thresh: 2.0  # px/ms
  min_track_len: 10

calib:
  fov_deg_guess: 75.0
  principal_point: auto
  horizon_frac_default: 0.4

export:
  codec: h264
  ffmpeg_path: ffmpeg
